### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, NaN)

### ISSUE THREAD

**Issue by TylerShaw** [atom-community/linter#804]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.4
**System**: Mac OS X 10.10.4
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.3.1

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, NaN)

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65

TypeError: Invalid Point: (NaN, NaN)
    at Function.module.exports.Point.assertValid (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:970:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:958:20)
    at TextBuffer.module.exports.TextBuffer.markRange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:683:46)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1406:41)
    at TextEditor.module.exports.TextEditor.markBufferRange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1272:59)
    at /Users/ts/.atom/packages/linter/lib/linter-views.coffee:207:64
    at Array.forEach (native)
    at LinterViews.renderPanelMarkers (/Users/ts/.atom/packages/linter/lib/linter-views.coffee:201:20)
    at LinterViews.render (/Users/ts/.atom/packages/linter/lib/linter-views.coffee:76:12)
    at /Users/ts/.atom/packages/linter/lib/linter-plus.coffee:40:30
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at MessageRegistry.updatePublic (/Users/ts/.atom/packages/linter/lib/message-registry.coffee:98:22)
    at /Users/ts/.atom/packages/linter/lib/message-registry.coffee:106:24
```

### Commands

```
     -0:42.5.0 grammar-selector:show (atom-text-editor.editor)
     -0:39.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:37.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:12.3.0 grammar-selector:show (atom-text-editor.editor)
     -0:09.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:07.9.0 core:save (a.inline-block)
```

### Config

```json
{
  "core": {
    "themes": [
      "isotope-ui",
      "monokai"
    ],
    "disabledPackages": [
      "autocomplete-jedi",
      "autocomplete",
      "markdown-format",
      "linter-golinter",
      "linter-gotype",
      "linter-govet"
    ],
    "ignoredNames": [
      ".DS_Store"
    ],
    "projectHome": "/Users/ts/Dropbox/Workspace",
    "audioBeep": false,
    "followSymlinks": true
  },
  "linter": {
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
angularjs, v0.3.0
atom-beautify, v0.28.8
autocomplete-python, v0.5.3
color-picker, v2.0.11
isotope-ui, v2.5.1
linter, v1.3.1
linter-bootlint, v0.0.6
linter-chktex, v1.0.0
linter-clang, v3.1.1
linter-cpplint, v0.1.4
linter-csslint, v1.0.0
linter-htmlhint, v0.0.17
linter-jshint, v1.1.4
linter-jsonlint, v0.1.4
linter-pylint, v0.2.2
linter-shellcheck, v0.0.8
linter-tidy, v1.0.1
monokai, v0.15.0
pigments, v0.9.3
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by k2b6s9j** [comment]
Mind sharing some information about the file you were editing when this error occurred?

**Comment by TylerShaw** [comment]
It was just a normal css file. there wasn't much in it. I copy and pasted the default pygments css and did some h1-h6 header tags, but nothing else. All of it is proper css. It has to do with displaying the linting errors in the minimap. Once I turned that off everything was good.

**Comment by k2b6s9j** [comment]
I'm going to go with `linter-csslint` is being naughty. Mind filing an
issue there?

**Comment by steelbrain** [comment]
@TylerShaw can you provide a minimal snippet that can repro this error please?

**Comment by Stephen304** [comment]
Here's the minimum (so far) that triggers it for me:

    ul.class li.subclass_1 .first {width:10%; float:left; font-size:22px; font-weight:100; padding:10px 0;}
    ul.class li.subclass_1 .second {width:90%; float:left; min-height: 85px;}
    
    ul.class li.subclass_2 .first {width:10%; float:left; font-size:22px; font-weight:100; padding:10px 0;}
    ul.class li.subclass_2 .second {width:90%; float:left; min-height: 85px;}
    
    ul.class li.subclass_3 .first {width:10%; float:left; font-size:22px; font-weight:100; padding:10px 0;}
    ul.class li.subclass_3 .second {width:90%; float:left; min-height: 85px;}
    
    ul.class li.subclass_4 .first {width:10%; float:left; font-size:22px; font-weight:100; padding:10px 0;}
    ul.class li.subclass_4 .second {width:90%; float:left; min-height: 85px;}
    
    ul.class li.subclass_5 .first {width:10%; float:left; font-size:22px; font-weight:100; padding:10px 0;}
    ul.class li.subclass_5 .second {width:90%; float:left; min-height: 85px;}

I'll update if I can minimize it more.

**Comment by Arcanemagus** [comment]
`linter-csslint` should have fixed this in v1.0.2, can you verify it works properly now?

**Comment by BMOv2600** [comment]
Just got the error as well, after I updated the package, then opened a css file.

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.3.2


### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, NaN)

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65

TypeError: Invalid Point: (NaN, NaN)
  at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65:15)
  at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:970:13)
  at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:958:20)
  at TextBuffer.module.exports.TextBuffer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:683:46)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1406:41)
  at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1272:59)
  at /Users/BMOre/.atom/packages/linter/lib/linter-views.coffee:115:55
  at Array.forEach (native)
  at LinterViews.renderPanelMarkers (/Users/BMOre/.atom/packages/linter/lib/linter-views.coffee:113:11)
  at LinterViews.render (/Users/BMOre/.atom/packages/linter/lib/linter-views.coffee:43:6)
  at /Users/BMOre/.atom/packages/linter/lib/linter-plus.coffee:29:14
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at MessageRegistry.updatePublic (/Users/BMOre/.atom/packages/linter/lib/message-registry.coffee:55:16)
  at /Users/BMOre/.atom/packages/linter/lib/message-registry.coffee:57:31

```

### Commands

```
     -5:14.4.0 core:save-as (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:10 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:06.2.0 project-manager:save-project (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:04.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -5:00.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -5:00.6.0 focus (atom-workspace.workspace.scrollbars-visible-always.theme-zenburn.theme-one-dark-ui.white-cursor)
     -4:06.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:09.3.0 application:new-file (atom-text-editor.editor.is-focused)
     -1:07.9.0 core:paste (atom-text-editor.editor.is-focused)
     -1:04.4.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:46.3.0 core:copy (atom-text-editor.editor.is-focused)
     -0:44.6.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:42.3.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
     -0:35.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:35 core:copy (atom-text-editor.editor.is-focused)
     -0:33.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-zenburn.theme-one-dark-ui.white-cursor.find-visible)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "zenburn"
    ],
    "disabledPackages": [
      "css-color-underline",
      "css-color-highlight",
      "atom-css-class-checker",
      "linter-xmllint",
      "webbox-color",
      "csscomb",
      "css-comb"
    ],
    "projectHome": "/Users/BMOre/desktop/bmo/my_site"
  },
  "linter": {
    "lintOnFly": true,
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.10
atom-minify, v0.2.2
auto-indent, v0.5.0
bezier-curve-editor, v0.7.2
color-picker, v2.0.11
editorconfig, v1.0.1
file-icons, v1.6.2
highlight-line, v0.11.0
indent-guide-improved, v1.4.1
linter, v1.3.2
linter-csslint, v1.0.2
linter-js-standard, v2.4.0
linter-jshint, v1.1.4
linter-php, v1.0.3
php-debug, v0.1.2
pigments, v0.9.3
project-manager, v1.15.11
tool-bar, v0.1.8
tool-bar-main, v0.0.8
white-cursor, v0.6.0
zenburn, v3.0.0

# Dev
No dev packages
```



```coffee
# User
atom-beautify, v0.28.10
atom-minify, v0.2.2
auto-indent, v0.5.0
bezier-curve-editor, v0.7.2
color-picker, v2.0.11
editorconfig, v1.0.1
file-icons, v1.6.2
highlight-line, v0.11.0
indent-guide-improved, v1.4.1
linter, v1.3.1
linter-csslint, v1.0.0
linter-js-standard, v2.4.0
linter-jshint, v1.1.4
linter-php, v1.0.3
php-debug, v0.1.2
pigments, v0.9.3
project-manager, v1.15.11
tool-bar, v0.1.8
tool-bar-main, v0.0.8
white-cursor, v0.6.0
zenburn, v3.0.0

# Dev
No dev packages
```

**Comment by robneu** [comment]
Still broken here too.

**Comment by Arcanemagus** [comment]
@robneu @BMOv2600 This is working fine with me with the code @Stephen304 posted, can you post some code that this is still reproducible for for you?

**Comment by Stephen304** [comment]
Yeah seems to be fixed for me for the 1k line css file my example was from.

**Comment by Arcanemagus** [comment]
I've pushed out v1.0.5 of `linter-csslint`, @BMOv2600 @TylerShaw are you still having issues?

This issue should probably be closed in favor of https://github.com/AtomLinter/linter-csslint/issues/37 as this isn't an issue with the `linter` package.

**Comment by inacent** [comment]
I use latest v. 1.0.5 of linter-csslint and I still have the issue.

**Comment by steelbrain** [comment]
Please discuss on the issue in linter-csslint repo.
